package com.wf.system.mapper;

import com.wf.system.model.entity.AttrValue;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attr_value
     *
     * @mbg.generated
     */
    @Delete({
        "delete from attr_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attr_value
     *
     * @mbg.generated
     */
    @Insert({
        "insert into attr_value (id, value, ",
        "category_attr_id)",
        "values (#{id,jdbcType=INTEGER}, #{value,jdbcType=VARCHAR}, ",
        "#{categoryAttrId,jdbcType=INTEGER})"
    })
    int insert(AttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attr_value
     *
     * @mbg.generated
     */
    @InsertProvider(type=AttrValueSqlProvider.class, method="insertSelective")
    int insertSelective(AttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attr_value
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, value, category_attr_id",
        "from attr_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_attr_id", property="categoryAttrId", jdbcType=JdbcType.INTEGER)
    })
    AttrValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attr_value
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttrValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attr_value
     *
     * @mbg.generated
     */
    @Update({
        "update attr_value",
        "set value = #{value,jdbcType=VARCHAR},",
          "category_attr_id = #{categoryAttrId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AttrValue record);
}