package com.wf.system.mapper;

import com.wf.system.model.entity.AttrValue;
import org.apache.ibatis.jdbc.SQL;

public class AttrValueSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attr_value
	 * @mbg.generated
	 */
	public String insertSelective(AttrValue record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("attr_value");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=INTEGER}");
		}
		if (record.getValue() != null) {
			sql.VALUES("value", "#{value,jdbcType=VARCHAR}");
		}
		if (record.getCategoryAttrId() != null) {
			sql.VALUES("category_attr_id", "#{categoryAttrId,jdbcType=INTEGER}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attr_value
	 * @mbg.generated
	 */
	public String updateByPrimaryKeySelective(AttrValue record) {
		SQL sql = new SQL();
		sql.UPDATE("attr_value");
		if (record.getValue() != null) {
			sql.SET("value = #{value,jdbcType=VARCHAR}");
		}
		if (record.getCategoryAttrId() != null) {
			sql.SET("category_attr_id = #{categoryAttrId,jdbcType=INTEGER}");
		}
		sql.WHERE("id = #{id,jdbcType=INTEGER}");
		return sql.toString();
	}
}