package com.wf.system.mapper;

import com.wf.system.model.entity.FirstCategory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FirstCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from first_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into first_category (id, name, ",
        "descript)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{descript,jdbcType=VARCHAR})"
    })
    int insert(FirstCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated
     */
    @InsertProvider(type=FirstCategorySqlProvider.class, method="insertSelective")
    int insertSelective(FirstCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, descript",
        "from first_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="descript", property="descript", jdbcType=JdbcType.VARCHAR)
    })
    FirstCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=FirstCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FirstCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated
     */
    @Update({
        "update first_category",
        "set name = #{name,jdbcType=VARCHAR},",
          "descript = #{descript,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FirstCategory record);
}