package com.wf.system.mapper;

import com.wf.system.model.entity.FirstCategory;
import org.apache.ibatis.jdbc.SQL;

public class FirstCategorySqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table first_category
	 * @mbg.generated
	 */
	public String insertSelective(FirstCategory record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("first_category");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=INTEGER}");
		}
		if (record.getName() != null) {
			sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
		}
		if (record.getDescript() != null) {
			sql.VALUES("descript", "#{descript,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table first_category
	 * @mbg.generated
	 */
	public String updateByPrimaryKeySelective(FirstCategory record) {
		SQL sql = new SQL();
		sql.UPDATE("first_category");
		if (record.getName() != null) {
			sql.SET("name = #{name,jdbcType=VARCHAR}");
		}
		if (record.getDescript() != null) {
			sql.SET("descript = #{descript,jdbcType=VARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=INTEGER}");
		return sql.toString();
	}
}