package com.wf.system.mapper;

import com.wf.system.model.entity.ProductBasic;
import org.apache.ibatis.jdbc.SQL;

public class ProductBasicSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public String insertSelective(ProductBasic record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("product_basic");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getLeftNum() != null) {
            sql.VALUES("left_num", "#{leftNum,jdbcType=INTEGER}");
        }
        
        if (record.getStoreAddress() != null) {
            sql.VALUES("store_address", "#{storeAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getProductId() != null) {
            sql.VALUES("product_id", "#{productId,jdbcType=INTEGER}");
        }
        
        if (record.getAttrValueId() != null) {
            sql.VALUES("attr_value_id", "#{attrValueId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(ProductBasic record) {
        SQL sql = new SQL();
        sql.UPDATE("product_basic");
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=DECIMAL}");
        }
        
        if (record.getLeftNum() != null) {
            sql.SET("left_num = #{leftNum,jdbcType=INTEGER}");
        }
        
        if (record.getStoreAddress() != null) {
            sql.SET("store_address = #{storeAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getProductId() != null) {
            sql.SET("product_id = #{productId,jdbcType=INTEGER}");
        }
        
        if (record.getAttrValueId() != null) {
            sql.SET("attr_value_id = #{attrValueId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}