package com.wf.system.mapper;

import com.wf.system.model.entity.Product;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated
	 */
	@Delete({ "delete from product", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated
	 */
	@Insert({ "insert into product (id, name, ", "descript, category_brand_id, ", "pic)",
			"values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
			"#{descript,jdbcType=VARCHAR}, #{categoryBrandId,jdbcType=INTEGER}, ", "#{pic,jdbcType=LONGVARCHAR})" })
	int insert(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated
	 */
	@InsertProvider(type = ProductSqlProvider.class, method = "insertSelective")
	int insertSelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated
	 */
	@Select({ "select", "id, name, descript, category_brand_id, pic", "from product",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "descript", property = "descript", jdbcType = JdbcType.VARCHAR),
			@Result(column = "category_brand_id", property = "categoryBrandId", jdbcType = JdbcType.INTEGER),
			@Result(column = "pic", property = "pic", jdbcType = JdbcType.LONGVARCHAR) })
	Product selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated
	 */
	@UpdateProvider(type = ProductSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated
	 */
	@Update({ "update product", "set name = #{name,jdbcType=VARCHAR},", "descript = #{descript,jdbcType=VARCHAR},",
			"category_brand_id = #{categoryBrandId,jdbcType=INTEGER},", "pic = #{pic,jdbcType=LONGVARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKeyWithBLOBs(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated
	 */
	@Update({ "update product", "set name = #{name,jdbcType=VARCHAR},", "descript = #{descript,jdbcType=VARCHAR},",
			"category_brand_id = #{categoryBrandId,jdbcType=INTEGER}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Product record);
}