package com.wf.system.mapper;

import com.wf.system.model.entity.ProductBasic;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductBasicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    @Delete({
        "delete from product_basic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    @Insert({
        "insert into product_basic (id, price, ",
        "left_num, store_address, ",
        "product_id, attr_value_id)",
        "values (#{id,jdbcType=INTEGER}, #{price,jdbcType=DECIMAL}, ",
        "#{leftNum,jdbcType=INTEGER}, #{storeAddress,jdbcType=VARCHAR}, ",
        "#{productId,jdbcType=INTEGER}, #{attrValueId,jdbcType=INTEGER})"
    })
    int insert(ProductBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    @InsertProvider(type=ProductBasicSqlProvider.class, method="insertSelective")
    int insertSelective(ProductBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, price, left_num, store_address, product_id, attr_value_id",
        "from product_basic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="left_num", property="leftNum", jdbcType=JdbcType.INTEGER),
        @Result(column="store_address", property="storeAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.INTEGER),
        @Result(column="attr_value_id", property="attrValueId", jdbcType=JdbcType.INTEGER)
    })
    ProductBasic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ProductBasicSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProductBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    @Update({
        "update product_basic",
        "set price = #{price,jdbcType=DECIMAL},",
          "left_num = #{leftNum,jdbcType=INTEGER},",
          "store_address = #{storeAddress,jdbcType=VARCHAR},",
          "product_id = #{productId,jdbcType=INTEGER},",
          "attr_value_id = #{attrValueId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductBasic record);
}