package com.wf.system.mapper;

import com.wf.system.model.entity.RelatedBrandCategory;
import org.apache.ibatis.jdbc.SQL;

public class RelatedBrandCategorySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    public String insertSelective(RelatedBrandCategory record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("related_brand_category");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSecondCategoryId() != null) {
            sql.VALUES("second_category_id", "#{secondCategoryId,jdbcType=INTEGER}");
        }
        
        if (record.getBrandId() != null) {
            sql.VALUES("brand_id", "#{brandId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(RelatedBrandCategory record) {
        SQL sql = new SQL();
        sql.UPDATE("related_brand_category");
        
        if (record.getSecondCategoryId() != null) {
            sql.SET("second_category_id = #{secondCategoryId,jdbcType=INTEGER}");
        }
        
        if (record.getBrandId() != null) {
            sql.SET("brand_id = #{brandId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}