package com.wf.system.mapper;

import com.wf.system.model.entity.RelatedBrandCategory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RelatedBrandCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from related_brand_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into related_brand_category (id, second_category_id, ",
        "brand_id)",
        "values (#{id,jdbcType=INTEGER}, #{secondCategoryId,jdbcType=INTEGER}, ",
        "#{brandId,jdbcType=INTEGER})"
    })
    int insert(RelatedBrandCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    @InsertProvider(type=RelatedBrandCategorySqlProvider.class, method="insertSelective")
    int insertSelective(RelatedBrandCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, second_category_id, brand_id",
        "from related_brand_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="second_category_id", property="secondCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER)
    })
    RelatedBrandCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=RelatedBrandCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RelatedBrandCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table related_brand_category
     *
     * @mbg.generated
     */
    @Update({
        "update related_brand_category",
        "set second_category_id = #{secondCategoryId,jdbcType=INTEGER},",
          "brand_id = #{brandId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RelatedBrandCategory record);
}