package com.wf.system.model.entity;

public class AttrValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attr_value.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attr_value.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attr_value.category_attr_id
     *
     * @mbg.generated
     */
    private Integer categoryAttrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attr_value.id
     *
     * @return the value of attr_value.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attr_value.id
     *
     * @param id the value for attr_value.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attr_value.value
     *
     * @return the value of attr_value.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attr_value.value
     *
     * @param value the value for attr_value.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attr_value.category_attr_id
     *
     * @return the value of attr_value.category_attr_id
     *
     * @mbg.generated
     */
    public Integer getCategoryAttrId() {
        return categoryAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attr_value.category_attr_id
     *
     * @param categoryAttrId the value for attr_value.category_attr_id
     *
     * @mbg.generated
     */
    public void setCategoryAttrId(Integer categoryAttrId) {
        this.categoryAttrId = categoryAttrId;
    }
}