package com.wf.system.model.entity;

import java.math.BigDecimal;

public class ProductBasic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.left_num
     *
     * @mbg.generated
     */
    private Integer leftNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.store_address
     *
     * @mbg.generated
     */
    private String storeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.attr_value_id
     *
     * @mbg.generated
     */
    private Integer attrValueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.id
     *
     * @return the value of product_basic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_basic.id
     *
     * @param id the value for product_basic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.price
     *
     * @return the value of product_basic.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_basic.price
     *
     * @param price the value for product_basic.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.left_num
     *
     * @return the value of product_basic.left_num
     *
     * @mbg.generated
     */
    public Integer getLeftNum() {
        return leftNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_basic.left_num
     *
     * @param leftNum the value for product_basic.left_num
     *
     * @mbg.generated
     */
    public void setLeftNum(Integer leftNum) {
        this.leftNum = leftNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.store_address
     *
     * @return the value of product_basic.store_address
     *
     * @mbg.generated
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_basic.store_address
     *
     * @param storeAddress the value for product_basic.store_address
     *
     * @mbg.generated
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress == null ? null : storeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.product_id
     *
     * @return the value of product_basic.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_basic.product_id
     *
     * @param productId the value for product_basic.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.attr_value_id
     *
     * @return the value of product_basic.attr_value_id
     *
     * @mbg.generated
     */
    public Integer getAttrValueId() {
        return attrValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_basic.attr_value_id
     *
     * @param attrValueId the value for product_basic.attr_value_id
     *
     * @mbg.generated
     */
    public void setAttrValueId(Integer attrValueId) {
        this.attrValueId = attrValueId;
    }
}