package com.wf.system.model.entity;

public class RelatedBrandCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column related_brand_category.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column related_brand_category.second_category_id
	 * @mbg.generated
	 */
	private Integer secondCategoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column related_brand_category.brand_id
	 * @mbg.generated
	 */
	private Integer brandId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column related_brand_category.id
	 * @return  the value of related_brand_category.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column related_brand_category.id
	 * @param id  the value for related_brand_category.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column related_brand_category.second_category_id
	 * @return  the value of related_brand_category.second_category_id
	 * @mbg.generated
	 */
	public Integer getSecondCategoryId() {
		return secondCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column related_brand_category.second_category_id
	 * @param secondCategoryId  the value for related_brand_category.second_category_id
	 * @mbg.generated
	 */
	public void setSecondCategoryId(Integer secondCategoryId) {
		this.secondCategoryId = secondCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column related_brand_category.brand_id
	 * @return  the value of related_brand_category.brand_id
	 * @mbg.generated
	 */
	public Integer getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column related_brand_category.brand_id
	 * @param brandId  the value for related_brand_category.brand_id
	 * @mbg.generated
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}
}